### ISSUE TITLE
Validation error when reading crsloc.ini with only one item

### ISSUE THREAD

**Issue by tim-vd-aardweg** [Deltares/HYDROLIB-core#638] opened 2024-05-02 08:31 UTC
**Describe the bug**
When trying to import and .mdu file that references a crsloc.ini that only has one item in it, causes a validation error:

>         if validation_error:
>            raise validation_error
>            pydantic.v1.error_wrappers.ValidationError: 1 validation error for FMModel
>            geometry -> crossLocFile -> crsloc.ini -> crosssection
>              value is not a valid list (type=type_error.list)

**Expected behavior**
HYDROLIB-core reads the crsloc.ini file and creates a list with only one entry.

**Additional context**
I found this for CrossSectionLocations, but it may happen with other types that are lists as well. So it may be worth it to look into those cases as well.

**Comment by veenstrajelmer** [comment] 2024-07-08 08:54
Duplicate of https://github.com/Deltares/HYDROLIB-core/issues/680 and that one has reproducible code.

**Closed by veenstrajelmer** 2024-07-08 08:54 UTC
Labels: type: bug
