### ISSUE TITLE
RR open water node is not valid in hydrolib

### ISSUE THREAD

**Issue by Kreef** [Deltares/HYDROLIB-core#232] opened 2022-05-09 12:10 UTC
When creating an openwater node in D-Hydro, it gets assigned model type 21, netter type 67 in rr\3b_NOD.tp. When loading this in hydrolib through a DIMR model, the model type is not recognized and the RR model not validated.

Adding "67: 21" to nodetypes_netter_to_rr in hydrolib/core/io/rr/topology/models.py solves the issue.

**Comment by arthurvd** [comment] 2022-07-08 11:51
Was fixed in/duplicate of #256.

**Closed by arthurvd** 2022-07-08 11:51 UTC
