### ISSUE TITLE
Structuremodel cannot be created from existing structuremodel with small change

### ISSUE THREAD

**Issue by rhutten** [Deltares/HYDROLIB-core#255] opened 2022-06-27 08:31 UTC
**Describe the bug**
A D-HyDAMO model (FM model) is read into a Jupyter notebook using hydrolib-core functionalities.  The structuremodel is converted to a dataframe and a pump capacity is changed. In order to create StructureModel from df_structures, several dataframe adjustments are needed. See attached figure.
![image](https://user-images.githubusercontent.com/55204099/175894823-e9f13b23-d29f-412d-8f8f-58d1b458674e.png)
 
More information can be found locally in Arthur's postbox.

**To Reproduce**
1. Please run the Notebook to cell  with "Enkele extra aanpassingen waren noodzakelijk". Do not run this cell
2. Run "structures_new = StructureModel(filepath = None, structure=df_structures.to_dict("records"))"
3. Several validationErrors pop-up
4. Please run the cell with "Enkele extra aanpassingen waren noodzakelijk"

**Expected behavior**
The model is a valid model and has no validationError when reading the model. Since only a float is changed in the dataframe (pump capacity), no validationError should pop-up during the creation of the structureModel from the dataframe.

**Screenshots**
See above

**Comment by arthurvd** [comment] 2022-07-07 12:25
This is caused by the same issue as described in #201.
We don't have a code fix for this: the user should make sure there are no NaN values in the dataframe.
Use, for example in your notebook:
```python
df2=df_structures.astype(object)
df2.where(pd.notnull(df2),None, inplace=True)
```

**Closed by arthurvd** 2022-07-07 12:25 UTC
Labels: bug
