### ISSUE TITLE
Incorrect validation error occurs when reading mdu-file 

### ISSUE THREAD

**Issue by rhutten** [Deltares/HYDROLIB-core#116] opened 2021-10-28 20:21 UTC
Incorrect validation error occurs when reading partitionFile parameter under [geometry]
![image](https://user-images.githubusercontent.com/55204099/139328326-5e575381-36d4-446a-9d74-6bd48f53bd83.png)

**Comment by arthurvd** [comment] 2022-07-08 11:54
Was fixed in/duplicate of: #208.

**Closed by arthurvd** 2022-07-08 11:54 UTC
