### ISSUE TITLE
1d2d link generation changes when updating meshkernel 1.0.0 to 2.0.2

### ISSUE THREAD

**Issue by RuudHurkmans** [Deltares/HYDROLIB-core#547] opened 2023-05-19 08:42 UTC
Link generation 1d to 2d produces different results between Meshkernel versions 1.0.0 and 2.0.2. 

**To Reproduce**
1. Go Hydrolib branch "environment: update toml-and-yaml"
2. Make sure hydrolib-core version is 0..4.1 (meskernel 1.0.0 is installed)
3. run unit test "tests/dhydamo/geometry/test_mesh.py/test_links1d2d_add_links_1d_to_2d"; first activate the code plotting the figure (it is commented outto enable CGI); This results in the left screenshot blow.
4. Repeat the above with hydrolib-core version 0.5.2 (meshkernel 2.0.2). The right screenshot is produced.

**Expected behavior**
I expect two identical figures.

**Screenshots**
![image](https://github.com/Deltares/HYDROLIB-core/assets/59835874/4442de59-0ab5-49f9-a911-6f30fcba3171)

**Version info (please complete the following information):**
 - OS: Windows 11
 - D Hydamo 1.0.1

**Additional context**
The relevant code in hydrolib core hasn't changed between versions (I checked) neither has D-Hydamo. This suggests the change is due to the update in Meshkernel. It only affects the function 'contacts_compute_single' in meshkernel, other variants (contacts_compute_with_points, contacts_compute_boundary) behave the same in both versions.

**Comment by lucacarniato** [comment] 2023-07-03 06:58
This issue will be resolved in the upcoming version of MeshKernelPy (v2.1.0). Please refer to the release notes for more information.

**Comment by veenstrajelmer** [comment] 2024-01-15 12:46
@RuudHurkmans could you check if this issue is indeed resolved with meshkernelpy 2.1.0? I found [your test](https://github.com/Deltares/HYDROLIB/blob/4c56fb7a179fe738ab1eaa05a3e3048baadff1b3/tests/dhydamo/geometry/test_mesh.py#L445) but could not reproduce your code. If it is still an issue, could you provide a minimal reproducible example that only uses HYDROLIB-core imports?

**Comment by veenstrajelmer** [comment] 2024-05-01 12:39
@RuudHurkmans can we indeed close this issue now? I think this was one of the cases we discussed with @lucacarniato right?

**Comment by veenstrajelmer** [comment] 2024-06-07 13:04
This should be resolved with newer meshkernel versions, at least with 4.2.0

**Closed by veenstrajelmer** 2024-06-07 13:04 UTC
Labels: type: bug, type: question, priority: high
