### ISSUE TITLE
Add developer documentation

### ISSUE THREAD

**Issue by evetion** [Deltares/HYDROLIB-core#16] opened 2021-07-13 14:27 UTC
Branch structure, squash merge.

**Comment by priscavdsluis** [comment] 2023-04-03 07:25
This issue seems a duplicate of #481

**Comment by evetion** [comment] 2023-04-03 08:02
> This issue seems a duplicate of #481 

Issue #481 is a duplicate of this issue 😜

**Comment by priscavdsluis** [comment] 2024-04-09 14:15
Closing issue as #481 has been done and dev guide is in place.

**Closed by priscavdsluis** 2024-04-09 14:15 UTC
Labels: type: documentation
